// words.js - This acts as your game's database!

const wordDatabase = {
    3: [
        { pattern: ["?", "A", "T"], answer: "C", icon: "🐈", turkish: "Kedi" },
        { pattern: ["?", "A", "T"], answer: "F", icon: "⚖️", turkish: "Şişman / Yağ" },
        { pattern: ["?", "A", "T"], answer: "H", icon: "🎩", turkish: "Şapka" },
        { pattern: ["?", "A", "T"], answer: "M", icon: "🚪", turkish: "Paspas / Minder" },
        { pattern: ["?", "A", "T"], answer: "P", icon: "👋", turkish: "Hafifçe vurmak" },
        { pattern: ["?", "A", "T"], answer: "R", icon: "🐀", turkish: "Fare" },
        { pattern: ["?", "A", "T"], answer: "V", icon: "🛢️", turkish: "Fıçı" },
        { pattern: ["B", "?", "T"], answer: "U", icon: "🤔", turkish: "Ama / Fakat" },
        { pattern: ["B", "A", "?"], answer: "D", icon: "👎", turkish: "Kötü" },
        { pattern: ["B", "A", "?"], answer: "G", icon: "👜", turkish: "Çanta" },
        { pattern: ["B", "A", "?"], answer: "N", icon: "🚫", turkish: "Yasak" },
        { pattern: ["B", "A", "?"], answer: "R", icon: "🍫", turkish: "Çubuk / Bar" },
        { pattern: ["?", "A", "N"], answer: "B", icon: "🛑", turkish: "Yasaklamak" },
        { pattern: ["?", "A", "N"], answer: "C", icon: "🥫", turkish: "Teneke Kutu / Yapabilmek" },
        { pattern: ["?", "A", "N"], answer: "F", icon: "🌀", turkish: "Vantilatör / Taraftar" },
        { pattern: ["?", "A", "N"], answer: "M", icon: "👨", turkish: "Adam" },
        { pattern: ["?", "A", "N"], answer: "T", icon: "☀️", turkish: "Bronzlaşmak" },
        { pattern: ["?", "A", "N"], answer: "V", icon: "🚐", turkish: "Minibüs" },
        { pattern: ["P", "?", "N"], answer: "E", icon: "🖊️", turkish: "Tükenmez Kalem" },
        { pattern: ["P", "?", "N"], answer: "I", icon: "📌", turkish: "Toplu İğne" },
        { pattern: ["P", "?", "N"], answer: "U", icon: "🎭", turkish: "Kelime Oyunu" },
        { pattern: ["P", "A", "?"], answer: "D", icon: "📝", turkish: "Bloknot / Ped" },
        { pattern: ["P", "A", "?"], answer: "L", icon: "🤝", turkish: "Dost / Arkadaş" },
        { pattern: ["P", "A", "?"], answer: "T", icon: "👋", turkish: "Hafifçe Vurmak" },
        { pattern: ["P", "A", "?"], answer: "W", icon: "🐾", turkish: "Pati" },
        { pattern: ["P", "A", "?"], answer: "Y", icon: "💵", turkish: "Ödemek" },
        { pattern: ["?", "O", "T"], answer: "C", icon: "🛏️", turkish: "Karyola" },
        { pattern: ["?", "O", "T"], answer: "D", icon: "⏺️", turkish: "Nokta" },
        { pattern: ["?", "O", "T"], answer: "H", icon: "🔥", turkish: "Sıcak" },
        { pattern: ["?", "O", "T"], answer: "L", icon: "📚", turkish: "Çok / Parti" },
        { pattern: ["?", "O", "T"], answer: "N", icon: "❌", turkish: "Değil" },
        { pattern: ["?", "O", "T"], answer: "R", icon: "🤢", turkish: "Çürümek" },
        { pattern: ["P", "?", "T"], answer: "A", icon: "👋", turkish: "Okşamak" },
        { pattern: ["P", "?", "T"], answer: "E", icon: "🐶", turkish: "Evcil Hayvan" },
        { pattern: ["P", "?", "T"], answer: "I", icon: "🕳️", turkish: "Çukur" },
        { pattern: ["P", "O", "?"], answer: "D", icon: "🫛", turkish: "Koza" },
        { pattern: ["P", "O", "?"], answer: "P", icon: "🎈", turkish: "Patlamak" },
        { pattern: ["?", "U", "G"], answer: "H", icon: "🫂", turkish: "Sarılmak" },
        { pattern: ["?", "U", "G"], answer: "J", icon: "🏺", turkish: "Sürahi" },
        { pattern: ["?", "U", "G"], answer: "L", icon: "🏋️", turkish: "Sürüklemek / Taşımak" },
        { pattern: ["?", "U", "G"], answer: "M", icon: "☕", turkish: "Kupa" },
        { pattern: ["?", "U", "G"], answer: "P", icon: "🐕", turkish: "Pug (Köpek Cinsi)" },
        { pattern: ["?", "U", "G"], answer: "R", icon: "🧞", turkish: "Halı / Kilim" },
        { pattern: ["?", "U", "G"], answer: "T", icon: "🧗", turkish: "Güçle Çekmek" },
        { pattern: ["B", "?", "G"], answer: "A", icon: "🎒", turkish: "Çanta" },
        { pattern: ["B", "?", "G"], answer: "E", icon: "🥺", turkish: "Yalvarmak" },
        { pattern: ["B", "?", "G"], answer: "I", icon: "🐘", turkish: "Büyük" },
        { pattern: ["B", "?", "G"], answer: "O", icon: "🐸", turkish: "Bataklık" },
        { pattern: ["B", "U", "?"], answer: "D", icon: "🌱", turkish: "Tomurcuk" },
        { pattern: ["B", "U", "?"], answer: "M", icon: "🚶", turkish: "Serseri / Tembel" },
        { pattern: ["B", "U", "?"], answer: "N", icon: "🥯", turkish: "Çörek" },
        { pattern: ["B", "U", "?"], answer: "S", icon: "🚌", turkish: "Otobüs" },
        { pattern: ["B", "U", "?"], answer: "T", icon: "🤷", turkish: "Ama" },
        { pattern: ["?", "I", "P"], answer: "D", icon: "🥣", turkish: "Daldırmak" },
        { pattern: ["?", "I", "P"], answer: "H", icon: "🦴", turkish: "Kalça" },
        { pattern: ["?", "I", "P"], answer: "L", icon: "👄", turkish: "Dudak" },
        { pattern: ["?", "I", "P"], answer: "N", icon: "🤏", turkish: "Çimdiklemek" },
        { pattern: ["?", "I", "P"], answer: "R", icon: "📄", turkish: "Yırtmak" },
        { pattern: ["?", "I", "P"], answer: "S", icon: "🧃", turkish: "Yudumlamak" },
        { pattern: ["?", "I", "P"], answer: "Z", icon: "🤐", turkish: "Fermuar" },
        { pattern: ["T", "?", "P"], answer: "A", icon: "🚰", turkish: "Musluk / Tıklamak" },
        { pattern: ["T", "?", "P"], answer: "O", icon: "⛰️", turkish: "Üst / Zirve" },
        { pattern: ["T", "I", "?"], answer: "E", icon: "👔", turkish: "Kravat / Bağlamak" },
        { pattern: ["T", "I", "?"], answer: "N", icon: "🥫", turkish: "Teneke" },
        { pattern: ["?", "E", "T"], answer: "B", icon: "🎰", turkish: "Bahis" },
        { pattern: ["?", "E", "T"], answer: "G", icon: "🤲", turkish: "Almak / Elde Etmek" },
        { pattern: ["?", "E", "T"], answer: "J", icon: "✈️", turkish: "Jet Uçağı" },
        { pattern: ["?", "E", "T"], answer: "L", icon: "👍", turkish: "İzin Vermek" },
        { pattern: ["?", "E", "T"], answer: "P", icon: "🐈", turkish: "Evcil Hayvan" },
        { pattern: ["?", "E", "T"], answer: "S", icon: "⚙️", turkish: "Set / Ayarlamak" },
        { pattern: ["?", "E", "T"], answer: "V", icon: "🩺", turkish: "Veteriner" },
        { pattern: ["N", "?", "T"], answer: "U", icon: "🥜", turkish: "Kuruyemiş" },
        { pattern: ["N", "E", "?"], answer: "W", icon: "✨", turkish: "Yeni" },
        { pattern: ["?", "I", "N"], answer: "B", icon: "🗑️", turkish: "Kutu / Çöp Kutusu" },
        { pattern: ["?", "I", "N"], answer: "K", icon: "👨‍👩‍👦", turkish: "Akraba / Soy" },
        { pattern: ["?", "I", "N"], answer: "P", icon: "📍", turkish: "Toplu İğne" },
        { pattern: ["?", "I", "N"], answer: "S", icon: "😈", turkish: "Günah" },
        { pattern: ["?", "I", "N"], answer: "T", icon: "🥫", turkish: "Teneke Kutu" },
        { pattern: ["?", "I", "N"], answer: "W", icon: "🏆", turkish: "Kazanmak" },
        { pattern: ["F", "?", "N"], answer: "A", icon: "🪭", turkish: "Taraftar / Vantilatör" },
        { pattern: ["F", "?", "N"], answer: "U", icon: "🎉", turkish: "Eğlence" },
        { pattern: ["F", "I", "?"], answer: "B", icon: "🤥", turkish: "Küçük Yalan" },
        { pattern: ["F", "I", "?"], answer: "G", icon: "🍃", turkish: "İncir" },
        { pattern: ["F", "I", "?"], answer: "X", icon: "🔧", turkish: "Tamir Etmek" },
        { pattern: ["?", "A", "P"], answer: "G", icon: "🌉", turkish: "Boşluk / Uçurum" },
        { pattern: ["?", "A", "P"], answer: "L", icon: "🏃", turkish: "Tur / Kucak" },
        { pattern: ["?", "A", "P"], answer: "M", icon: "🗺️", turkish: "Harita" },
        { pattern: ["?", "A", "P"], answer: "N", icon: "😴", turkish: "Şekerleme Yapmak" },
        { pattern: ["?", "A", "P"], answer: "R", icon: "🎤", turkish: "Rap / Sertçe Vurmak" },
        { pattern: ["?", "A", "P"], answer: "S", icon: "🍁", turkish: "Özsuyu" },
        { pattern: ["?", "A", "P"], answer: "T", icon: "🚰", turkish: "Musluk" },
        { pattern: ["?", "A", "P"], answer: "Y", icon: "🗣️", turkish: "Havlamak / Gevezelik Etmek" },
        { pattern: ["C", "?", "P"], answer: "O", icon: "👮", turkish: "Polis" },
        { pattern: ["C", "?", "P"], answer: "U", icon: "☕", turkish: "Fincan / Kupa" },
        { pattern: ["C", "A", "?"], answer: "B", icon: "🚕", turkish: "Taksi" },
        { pattern: ["C", "A", "?"], answer: "D", icon: "😒", turkish: "Kaba Adam" },
        { pattern: ["C", "A", "?"], answer: "M", icon: "📷", turkish: "Kamera (Kısa)" },
        { pattern: ["C", "A", "?"], answer: "N", icon: "🥫", turkish: "Teneke Kutu" },
        { pattern: ["C", "A", "?"], answer: "R", icon: "🚗", turkish: "Araba" },
        { pattern: ["C", "A", "?"], answer: "T", icon: "🐱", turkish: "Kedi" },
        { pattern: ["?", "O", "P"], answer: "C", icon: "👮", turkish: "Polis" },
        { pattern: ["?", "O", "P"], answer: "M", icon: "🧹", turkish: "Paspas" },
        { pattern: ["?", "O", "P"], answer: "P", icon: "💥", turkish: "Patlamak" },
        { pattern: ["?", "O", "P"], answer: "T", icon: "🔝", turkish: "Üst" },
        { pattern: ["H", "?", "P"], answer: "I", icon: "🦴", turkish: "Kalça" },
        { pattern: ["H", "O", "?"], answer: "G", icon: "🐖", turkish: "Domuz" },
        { pattern: ["H", "O", "?"], answer: "T", icon: "🥵", turkish: "Sıcak" },
        { pattern: ["H", "O", "?"], answer: "W", icon: "❓", turkish: "Nasıl" },
        { pattern: ["?", "A", "D"], answer: "B", icon: "👎", turkish: "Kötü" },
        { pattern: ["?", "A", "D"], answer: "D", icon: "👨‍👧", turkish: "Baba" },
        { pattern: ["?", "A", "D"], answer: "F", icon: "🕶️", turkish: "Geçici Moda / Heves" },
        { pattern: ["?", "A", "D"], answer: "P", icon: "📝", turkish: "Bloknot / Ped" },
        { pattern: ["?", "A", "D"], answer: "S", icon: "😢", turkish: "Üzgün" },
        { pattern: ["M", "?", "D"], answer: "U", icon: "💩", turkish: "Çamur" },
        { pattern: ["M", "A", "?"], answer: "C", icon: "🧥", turkish: "Yağmurluk (Mac)" },
        { pattern: ["M", "A", "?"], answer: "N", icon: "👨", turkish: "Adam" },
        { pattern: ["M", "A", "?"], answer: "P", icon: "🗺️", turkish: "Harita" },
        { pattern: ["M", "A", "?"], answer: "T", icon: "🚪", turkish: "Paspas" },
        { pattern: ["M", "A", "?"], answer: "W", icon: "👄", turkish: "Hayvan Ağzı / Mide" },
        { pattern: ["?", "E", "N"], answer: "D", icon: "🐻", turkish: "İn / Mağara" },
        { pattern: ["?", "E", "N"], answer: "H", icon: "🐔", turkish: "Tavuk" },
        { pattern: ["?", "E", "N"], answer: "M", icon: "👨‍👨‍👦", turkish: "Adamlar (Çoğul)" },
        { pattern: ["?", "E", "N"], answer: "P", icon: "🖊️", turkish: "Tükenmez Kalem" },
        { pattern: ["T", "?", "N"], answer: "A", icon: "☀️", turkish: "Bronzlaşmak" },
        { pattern: ["T", "?", "N"], answer: "I", icon: "🥫", turkish: "Teneke" },
        { pattern: ["T", "?", "N"], answer: "O", icon: "🐘", turkish: "Ton (Ağırlık)" },
        { pattern: ["T", "E", "?"], answer: "A", icon: "🍵", turkish: "Çay" },
        { pattern: ["?", "O", "G"], answer: "B", icon: "🐸", turkish: "Bataklık" },
        { pattern: ["?", "O", "G"], answer: "C", icon: "⚙️", turkish: "Dişli" },
        { pattern: ["?", "O", "G"], answer: "D", icon: "🐕", turkish: "Köpek" },
        { pattern: ["?", "O", "G"], answer: "F", icon: "🌫️", turkish: "Sis" },
        { pattern: ["?", "O", "G"], answer: "H", icon: "🐖", turkish: "Domuz" },
        { pattern: ["?", "O", "G"], answer: "J", icon: "🏃", turkish: "Hafif Koşu" },
        { pattern: ["L", "?", "G"], answer: "A", icon: "⏳", turkish: "Gecikme (Lag)" },
        { pattern: ["L", "?", "G"], answer: "E", icon: "🦵", turkish: "Bacak" },
        { pattern: ["L", "O", "?"], answer: "T", icon: "📦", turkish: "Çok / Parti" },
        { pattern: ["L", "O", "?"], answer: "W", icon: "📉", turkish: "Düşük" },
        { pattern: ["?", "U", "N"], answer: "B", icon: "🥯", turkish: "Çörek" },
        { pattern: ["?", "U", "N"], answer: "F", icon: "🎉", turkish: "Eğlence" },
        { pattern: ["?", "U", "N"], answer: "G", icon: "🔫", turkish: "Silah" },
        { pattern: ["?", "U", "N"], answer: "N", icon: "⛪", turkish: "Rahibe" },
        { pattern: ["?", "U", "N"], answer: "P", icon: "🎭", turkish: "Kelime Oyunu" },
        { pattern: ["?", "U", "N"], answer: "R", icon: "🏃", turkish: "Koşmak" },
        { pattern: ["S", "?", "N"], answer: "I", icon: "😈", turkish: "Günah" },
        { pattern: ["S", "?", "N"], answer: "O", icon: "👦", turkish: "Erkek Evlat" },
        { pattern: ["S", "U", "?"], answer: "B", icon: "🥪", turkish: "Denizaltı / Sandviç" },
        { pattern: ["S", "U", "?"], answer: "M", icon: "➕", turkish: "Toplam" },
        { pattern: ["?", "U", "T"], answer: "B", icon: "🤷", turkish: "Ama / Fakat" },
        { pattern: ["?", "U", "T"], answer: "G", icon: "🩻", turkish: "Bağırsak / İçgüdü" },
        { pattern: ["?", "U", "T"], answer: "H", icon: "🛖", turkish: "Kulübe" },
        { pattern: ["?", "U", "T"], answer: "N", icon: "🥜", turkish: "Kuruyemiş" },
        { pattern: ["?", "U", "T"], answer: "R", icon: "🚜", turkish: "Tekerlek İzi / Rutin" },
        { pattern: ["C", "?", "T"], answer: "A", icon: "🐱", turkish: "Kedi" },
        { pattern: ["C", "?", "T"], answer: "O", icon: "🛏️", turkish: "Karyola" },
        { pattern: ["C", "U", "?"], answer: "B", icon: "🐻", turkish: "Yavru Hayvan" },
        { pattern: ["C", "U", "?"], answer: "D", icon: "🐄", turkish: "Geviş Getirmek" },
        { pattern: ["C", "U", "?"], answer: "E", icon: "🎱", turkish: "İşaret / Istaka" },
        { pattern: ["C", "U", "?"], answer: "P", icon: "☕", turkish: "Fincan / Kupa" },
        { pattern: ["?", "E", "D"], answer: "B", icon: "🛏️", turkish: "Yatak" },
        { pattern: ["?", "E", "D"], answer: "F", icon: "🍲", turkish: "Beslenmiş" },
        { pattern: ["?", "E", "D"], answer: "W", icon: "💍", turkish: "Evlenmek" },
        { pattern: ["R", "?", "D"], answer: "I", icon: "🗑️", turkish: "Kurtulmak" },
        { pattern: ["R", "?", "D"], answer: "O", icon: "🎣", turkish: "Çubuk / Olta" },
        { pattern: ["R", "E", "?"], answer: "F", icon: "⚽", turkish: "Hakem (Ref)" }
    ],
    
    // You will add the 4-letter words here later!
    4: [
        // { pattern: ["?", "O", "O", "K"], answer: "B", icon: "📖", turkish: "Kitap" },
    ],

    // You will add the 5-letter words here later!
    5: [],

    // You will add the 6-letter words here later!
    6: []
};
